//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smert
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public int order_item_id { get; set; }
        public int quantity { get; set; }
        public int item_price { get; set; }
        public int id_order { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_animal { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
