//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smert
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderReviews
    {
        public int review_id { get; set; }
        public int rating { get; set; }
        public string comment { get; set; }
        public int id_order { get; set; }
        public int id_customer { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
